[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
rust-version = "1.65.0"

[workspace.dependencies]
jlabel = { path = "crates/jlabel" }
jlabel-question = { path = "crates/jlabel-question" }
