name: release-please

on:
  push:
    branches: ["main"]

permissions: {} # Top-level permissions can often be left empty or set to read-all if job-level permissions are used

jobs:
  release-please:
    if: github.repository_owner == 'Mogyuchi'
    permissions:
      contents: write      # Needed for creating releases, tags, and updating manifest/config files
      pull-requests: write # Needed for creating/updating release PRs
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json
          skip-github-pull-request: ${{ startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'github-actions[bot]' }}
